# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

default:
  tags:
    - IRF

pages:
  script:
    # Path used by gitlab pages is "public"
    - mkdir public
    # Install reveal.js and copy to publication site
    - npm install --only=production
    - cp -rv css public/
    - cp -rv js public/
    - cp -rv dist public/
    - cp -rv plugin public/
    - cp -rv node_modules public/
    - cp -rv static public/
    - cp index.html public/
    
  artifacts:
    paths:
      - public

